# Generated by Django 5.2.5 on 2026-04-10 15:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email de connexion', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, null=True, unique=True)),
                ('role', models.CharField(choices=[('USER', 'Utilisateur Standard'), ('WITNESS', 'Témoin Certifié'), ('CHIEF', 'Chef de Localité'), ('ADMIN', 'Administrateur'), ('NOTARY', 'Notaire Certifié')], db_index=True, default='USER', max_length=20)),
                ('full_name', models.CharField(blank=True, help_text='Nom et Prénom (pas de chiffres)', max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='Benin', help_text='Pays de résidence', max_length=100)),
                ('departement', models.CharField(blank=True, help_text='Département', max_length=100, null=True)),
                ('commune', models.CharField(blank=True, help_text='Commune', max_length=100, null=True)),
                ('district', models.CharField(blank=True, help_text='Arrondissement', max_length=100, null=True)),
                ('village', models.CharField(blank=True, help_text='Quartier / Village', max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text="Compte vérifié par l'administration iLôt")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Réinitialisation',
                'verbose_name_plural': 'Tokens de Réinitialisation',
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('current_menu', models.CharField(default='HOME', max_length=50)),
                ('input_buffer', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session USSD',
                'db_table': 'ussd_sessions',
                'indexes': [models.Index(fields=['phone_number'], name='ussd_sessio_phone_n_a4ce08_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='app_users_role_fe5aa3_idx'),
        ),
    ]
