# Generated by Django 5.2.5 on 2026-04-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commune',
            field=models.CharField(blank=True, help_text='Commune', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='departement',
            field=models.CharField(blank=True, help_text='Département', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, help_text='Arrondissement', max_length=100, null=True),
        ),
    ]
