# Generated by Django 5.2.5 on 2026-04-09 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedSurveyor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(help_text="Numéro d'agrément officiel", max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Cabinet ou Administration', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Géomètre Agréé',
                'verbose_name_plural': 'Géomètres Agréés',
                'db_table': 'authorized_surveyors',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(default='Benin', help_text='Pays de la parcelle', max_length=100)),
                ('gps_centroid', models.JSONField(help_text='Point central {lat: float, lng: float}')),
                ('gps_boundaries', models.JSONField(help_text='Limites exactes [ {lat, lng}, ... ]')),
                ('area_sqm', models.FloatField(blank=True, help_text='Superficie en m²', null=True)),
                ('area_cadastral', models.CharField(blank=True, help_text='Superficie format cadastral (ex: 01ha 20a 15ca)', max_length=50, null=True)),
                ('departement', models.CharField(blank=True, help_text='Nom du département', max_length=100, null=True)),
                ('commune', models.CharField(blank=True, help_text='Nom de la commune', max_length=100, null=True)),
                ('district', models.CharField(blank=True, help_text="Nom de l'arrondissement", max_length=100, null=True)),
                ('village', models.CharField(blank=True, help_text='Quartier / Village', max_length=100, null=True)),
                ('surveyor_name', models.CharField(blank=True, help_text='Nom saisi (si hors liste)', max_length=255, null=True)),
                ('is_surveyor_validated', models.BooleanField(default=False, help_text='Le géomètre a-t-il certifié les mesures ?')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon / En attente'), ('PENDING_SURVEYOR', 'En attente attestation géomètre'), ('VALIDATING', 'En cours de validation communautaire'), ('VALIDATED', 'Sécurisé / Validé'), ('DISPUTED', 'En litige')], db_index=True, default='DRAFT', max_length=20)),
                ('owner_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='land_registry.authorizedsurveyor')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='property_media/')),
                ('media_type', models.CharField(choices=[('PHOTO_LAND', 'Photo du Terrain'), ('PHOTO_DOC', 'Photo Document Papier'), ('VIDEO_DRONE', 'Vidéo Drone'), ('LEGAL_DOC', 'Document Juridique (PDF/Scan)'), ('OTHER_MEDIA', 'Autre Média')], max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='land_registry.property')),
            ],
            options={
                'db_table': 'property_media',
            },
        ),
        migrations.CreateModel(
            name='PropertyWitness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Le témoin a-t-il validé son implication ?')),
                ('id_card_photo', models.FileField(blank=True, null=True, upload_to='witness_ids/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='land_registry.property')),
            ],
            options={
                'verbose_name': 'Témoin',
                'verbose_name_plural': 'Témoins',
                'db_table': 'property_witnesses',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties_status_e6008a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner_wallet'], name='properties_owner_w_fec567_idx'),
        ),
    ]
