# Generated by Django 5.2.5 on 2026-04-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0009_property_is_surveyor_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='commune',
            field=models.CharField(blank=True, help_text='Nom de la commune', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='departement',
            field=models.CharField(blank=True, help_text='Nom du département', max_length=100, null=True),
        ),
    ]
