# Generated by Django 5.2.5 on 2026-03-23 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_chatmessage_attachment_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('SALE', 'À vendre'), ('RENT', 'À louer')], default='SALE', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
