# Generated by Django 5.2.5 on 2026-04-09 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('boundary', models.JSONField(help_text='Polygone GeoJSON')),
            ],
            options={
                'db_table': 'geo_fences',
            },
        ),
        migrations.CreateModel(
            name='ValidationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_email', models.CharField(help_text='Email du demandeur', max_length=150)),
                ('gps_at_request', models.JSONField(help_text='Localisation {lat, lng}')),
                ('min_witnesses', models.IntegerField(default=3, help_text='Nombre minimum de témoins requis')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert aux votes'), ('COMPLETED', 'Validé (Consensus atteint)'), ('REJECTED', 'Rejeté (Fraude détectée)')], db_index=True, default='OPEN', max_length=20)),
            ],
            options={
                'db_table': 'validation_requests',
            },
        ),
        migrations.CreateModel(
            name='WitnessVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('witness_full_name', models.CharField(help_text='Nom et Prénoms complets', max_length=255)),
                ('witness_birth_date', models.DateField(blank=True, help_text='Date de naissance (YYYY-MM-DD)', null=True)),
                ('witness_id_number', models.CharField(help_text="Numéro de Passeport ou Carte d'Identité Nationale", max_length=100)),
                ('witness_phone', models.CharField(help_text='Numéro de téléphone', max_length=20)),
                ('witness_gps', models.JSONField(help_text='Localisation {lat, lng}')),
                ('vote_result', models.BooleanField(help_text='True=Valide, False=Fraude')),
            ],
            options={
                'db_table': 'witness_votes',
            },
        ),
    ]
