# Generated by Django 5.2.5 on 2026-04-07 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consensus', '0001_initial'),
        ('land_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='chief_user',
            field=models.ForeignKey(blank=True, help_text='Chef de zone responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validationrequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_requests', to='land_registry.property'),
        ),
        migrations.AddField(
            model_name='witnessvote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='consensus.validationrequest'),
        ),
        migrations.AddField(
            model_name='witnessvote',
            name='witness_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witness_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='witnessvote',
            unique_together={('request', 'witness_id_number')},
        ),
    ]
